//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Character/CharacterItemInteractionInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CharacterItemInteractionInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CharacterItemInteractionInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CharacterItemInteractionInput"",
    ""maps"": [
        {
            ""name"": ""ItemInteract"",
            ""id"": ""aefa4259-081f-4d96-9262-eeb3750e8bbb"",
            ""actions"": [
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""33c0c311-d23d-41f5-b4ae-2af300fbc59f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7c21a5d8-a3f5-47ba-ab6f-73e1949742f5"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ItemInteract
        m_ItemInteract = asset.FindActionMap("ItemInteract", throwIfNotFound: true);
        m_ItemInteract_Interact = m_ItemInteract.FindAction("Interact", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ItemInteract
    private readonly InputActionMap m_ItemInteract;
    private IItemInteractActions m_ItemInteractActionsCallbackInterface;
    private readonly InputAction m_ItemInteract_Interact;
    public struct ItemInteractActions
    {
        private @CharacterItemInteractionInput m_Wrapper;
        public ItemInteractActions(@CharacterItemInteractionInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Interact => m_Wrapper.m_ItemInteract_Interact;
        public InputActionMap Get() { return m_Wrapper.m_ItemInteract; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ItemInteractActions set) { return set.Get(); }
        public void SetCallbacks(IItemInteractActions instance)
        {
            if (m_Wrapper.m_ItemInteractActionsCallbackInterface != null)
            {
                @Interact.started -= m_Wrapper.m_ItemInteractActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_ItemInteractActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_ItemInteractActionsCallbackInterface.OnInteract;
            }
            m_Wrapper.m_ItemInteractActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
            }
        }
    }
    public ItemInteractActions @ItemInteract => new ItemInteractActions(this);
    public interface IItemInteractActions
    {
        void OnInteract(InputAction.CallbackContext context);
    }
}
